In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/HHS_Unaccompanied_Alien_Children_Program.csv")
df.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,"December 21, 2025",6,18,11,"2,484",14
1,"December 18, 2025",11,50,6,"2,472",16
2,"December 17, 2025",7,31,11,"2,481",10
3,"December 16, 2025",8,54,15,"2,468",9
4,"December 15, 2025",11,42,9,"2,470",7

In [2]:
df=df.sort_values('Date')
df=df.set_index('Date')
df.head(5)

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
Date,,,,,
"April 01, 2024",109,235,171,"7,271",172
"April 01, 2025",17,36,7,"2,191",12
"April 02, 2023",125,232,192,"7,981",304
"April 02, 2024",101,230,175,"7,340",132
"April 02, 2025",5,31,16,"2,208",3